FROM node:alpine3.20

WORKDIR /frontend
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build
# Dùng image phục vụ tĩnh để chạy frontend
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html

# Mở cổng 5173 (hoặc cổng do bạn chọn)
EXPOSE 80

# Lệnh khởi chạy Nginx
CMD ["nginx", "-g", "daemon off;"]